name: Build Image

on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: "Image type"
        required: true
        options:
          - amazonlinux
          - debian
          - ubuntu
        default: ubuntu
      version:
        description: "Version"
        required: true
        default: "22.04"

run-name: "Build Image - ${{ inputs.image }}:${{ inputs.version }}"

permissions:
  packages: write

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.image }}
          build-args: |
            VERSION=${{ inputs.version }}
          push: true
          provenance: false
          tags: ghcr.io/malang-dev/microstack-${{ inputs.image }}:${{ inputs.version }}
