name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build. List available versions at https://github.com/malang-dev/microstack-image/blob/master/kernel/config.json"
        required: true
        default: "5.10.199"

run-name: "Build Kernel - ${{ inputs.version }}"

permissions:
  packages: write

jobs:
  build:
    name: Build Kernel
    if: github.event.inputs.version != 'amazon'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Kernel Config
        id: kernel-config
        run: |
          URL=$(cat ./kernel/config.json | jq -r ".[] | select(.version == \"${{ inputs.version }}\") | .config_url")
          echo "url=$URL" >> "$GITHUB_OUTPUT"

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./kernel
          build-args: |
            KERNEL_VERSION=${{ inputs.version }}
            KERNEL_CONFIG=${{ steps.kernel-config.outputs.url }}
          push: true
          provenance: false
          tags: ghcr.io/malang-dev/microstack-kernel:${{ inputs.version }}

  build-amazon:
    name: Build Kernel Amazon
    if: github.event.inputs.version == 'amazon'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./kernel
          file: ./kernel/Dockerfile.amazon
          push: true
          provenance: false
          tags: ghcr.io/malang-dev/microstack-kernel:amazon
