name: Build Kernel

on: workflow_dispatch

permissions:
  packages: write

jobs:
  build:
    name: Build Kernel ${{ matrix.kernel.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel:
          - version: "6.1"
            config: https://raw.githubusercontent.com/firecracker-microvm/firecracker/main/resources/guest_configs/microvm-kernel-ci-x86_64-6.1.config
          - version: "5.10.199"
            config: https://raw.githubusercontent.com/firecracker-microvm/firecracker/main/resources/guest_configs/microvm-kernel-ci-x86_64-5.10.config
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./kernel
          build-args: |
            KERNEL_VERSION=${{ matrix.kernel.version }}
            KERNEL_CONFIG=${{ matrix.kernel.config }}
          push: true
          tags: ghcr.io/malang-dev/microstack-kernel:${{ matrix.kernel.version }}

  build-amazon:
    name: Build Kernel Amazon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./kernel
          file: Dockerfile.amazon
          push: true
          tags: ghcr.io/malang-dev/microstack-kernel:amazon
