name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      KERNEL_VERSION:
        type: choice
        description: "Kernel version to build"
        options:
          - 6.1
          - 5.10
        required: true

run-name: "Build Kernel ${{ github.event.inputs.KERNEL_VERSION }}"

jobs:
  build:
    name: Create kernel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./kernel/Dockerfile
          build-args: |
            KERNEL_VERSION=${{ github.event.inputs.KERNEL_VERSION }}
            KERNEL_CONFIG=https://raw.githubusercontent.com/firecracker-microvm/firecracker/main/resources/guest_configs/microvm-kernel-ci-x86_64-${{ github.event.inputs.KERNEL_VERSION }}.config
          push: true
          tags: malang-dev/microstack-kernel:${{ github.event.inputs.KERNEL_VERSION }}
